# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mach < Formula
  desc "Mach is a cli application for using docker to *quickly* and *easily* manage infrastructure and services through code."
  homepage "https://superterran.net/mach/"
  version "0.5.30"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/superterran/mach/releases/download/v0.5.30/mach_0.5.30_darwin_amd64.tar.gz"
      sha256 "2c493b01d53bc1f20d0a37727780644180b474a603ee42b0228e21cfa3be32e0"

      def install
        bin.install "mach"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/superterran/mach/releases/download/v0.5.30/mach_0.5.30_darwin_arm64.tar.gz"
      sha256 "c6de8f97096176018469a06d43af6b58c464c3c83e40862ded62b4f522f9a976"

      def install
        bin.install "mach"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/superterran/mach/releases/download/v0.5.30/mach_0.5.30_linux_amd64.tar.gz"
      sha256 "f1f0796365c048be0e8b6be20365ef2c66719fcecd4add3e6de52a2437f4ae53"

      def install
        bin.install "mach"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/superterran/mach/releases/download/v0.5.30/mach_0.5.30_linux_arm64.tar.gz"
      sha256 "670c9acc962519c8ce5450419f19756f39407f6139be93e43ea64df9907b0918"

      def install
        bin.install "mach"
      end
    end
  end

  depends_on "docker" => :optional
  depends_on "docker-compose" => :optional
  depends_on "git" => :optional

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/mach -h"
  end
end
