# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mach < Formula
  desc "Mach is a cli application for using docker to *quickly* and *easily* manage infrastructure and services through code."
  homepage "https://superterran.net/mach/"
  version "0.5.31"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/superterran/mach/releases/download/v0.5.31/mach_0.5.31_darwin_arm64.tar.gz"
      sha256 "3c5af25d822952b3fd568abbd178b24aa4d109de7fe635575c737602ffd42a7e"

      def install
        bin.install "mach"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/superterran/mach/releases/download/v0.5.31/mach_0.5.31_darwin_amd64.tar.gz"
      sha256 "3dd5c0bdb0128c53fe9a576f875d480ada8f027eb90ef70f3c2167b2c6680d6c"

      def install
        bin.install "mach"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/superterran/mach/releases/download/v0.5.31/mach_0.5.31_linux_amd64.tar.gz"
      sha256 "41de7ce2f89dba44ecdd8092223695af79369a7a01e3315657ae0db8b048673a"

      def install
        bin.install "mach"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/superterran/mach/releases/download/v0.5.31/mach_0.5.31_linux_arm64.tar.gz"
      sha256 "a39ce3d2706586eb07bcea5d0d67241ac13825469aad9034b54d06a2a5e80997"

      def install
        bin.install "mach"
      end
    end
  end

  depends_on "docker" => :optional
  depends_on "docker-compose" => :optional
  depends_on "git" => :optional

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/mach -h"
  end
end
