# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mach < Formula
  desc "Mach is a cli application for using docker to *quickly* and *easily* manage infrastructure and services through code."
  homepage "https://superterran.net/mach/"
  version "0.5.19"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/superterran/mach/releases/download/v0.5.19/mach_0.5.19_darwin_amd64.tar.gz"
      sha256 "3a227b155a6173958e0ffde56c12790c8ba566f871207617f9053a2dbab117fc"
    end
    if Hardware::CPU.arm?
      url "https://github.com/superterran/mach/releases/download/v0.5.19/mach_0.5.19_darwin_arm64.tar.gz"
      sha256 "b703a76c86b58e2a0aa368ec20d9ee0f9c831c558c1a66c19c34c2c3340c3181"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/superterran/mach/releases/download/v0.5.19/mach_0.5.19_linux_amd64.tar.gz"
      sha256 "1593e54d9aba0a3658e43ad77dbd2aa6c0f06d3d5371d4969da49e94e6b04013"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/superterran/mach/releases/download/v0.5.19/mach_0.5.19_linux_arm64.tar.gz"
      sha256 "9075eff5f91a5829e2cc7eead7c0b6f0942b3969893dfa7199b5db8a0fea068b"
    end
  end

  depends_on "docker" => :optional
  depends_on "docker-compose" => :optional
  depends_on "git" => :optional

  def install
    bin.install "mach"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/mach -h"
  end
end
